#!/bin/bash
# ==============================================================================
# Invoked by wmbusmeters via the "metershell" config when the FIRST telegram
# from a meter arrives.
#
#   wmbusmeters.conf: metershell=send_meter_discovery.sh "$METER_JSON" "$METER_DRIVER"
#
# Extracts the driver name from the first telegram's JSON, e.g.
#   { "driver":"amiplus", "id":"...", ... }
# and publishes the HA MQTT discovery payload(s) from
# /mqtt_discovery/<driver>.json - only this driver, nothing else.
#
# Exits cleanly (0) if anything is missing, wmbusmeters must never be blocked.
# ==============================================================================

METER_JSON="${1:-}"
if [ -z "$METER_JSON" ]; then
    exit 0
fi

METER_DRIVER="${2:-}"
if [ -z "$METER_DRIVER" ]; then
    exit 0
fi

TELEGRAM_FILE=$(mktemp)
DRIVER_FILE=$(mktemp)
DISCOVERY_FILE=$(mktemp)

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

printf '%s\n' "$METER_JSON" > $TELEGRAM_FILE
printf '%s\n' "$METER_DRIVER" > $DRIVER_FILE

trap 'rm -f "$TELEGRAM_FILE" "$DRIVER_FILE" "$DISCOVERY_FILE"' EXIT

# --- Resolve driver / id / name from the first telegram ----------------------
DRIVER=$(printf '%s' "$METER_JSON" | jq -r '.driver // empty' 2>/dev/null)
if [ -z "$DRIVER" ]; then
    echo "metershell: no driver in telegram, ignoring" >&2
    exit 0
fi

ID=$(printf '%s' "$METER_JSON" | jq -r '.id // empty' 2>/dev/null)
NAME="${METER_NAME:-}"
if [ -z "$NAME" ]; then
    NAME=$(printf '%s' "$METER_JSON" | jq -r '.name // empty' 2>/dev/null)
fi

if [ -z "$ID" ] || [ -z "$NAME" ]; then
    echo "metershell: telegram missing meter id or name, ignoring" >&2
    exit 0
fi

# --- Generate discovery json using to-ha-transform.xslq

xmq $TELEGRAM_FILE \
    transform --stringparam="drv=$DRIVER_FILE" $SCRIPT_DIR/to-ha-discovery.xslq \
    to-json | jq --sort-keys > $DISCOVERY_FILE

if [ "$3" != "" ]
then
    cp $DISCOVERY_FILE $3
    exit 0
fi

# --- MQTT publish helper (generated by run.sh, holds broker + credentials) ---
PUB=/wmbusmeters/mosquitto_pub.sh
if [ ! -x "$PUB" ]; then
    echo "metershell: no MQTT broker configured, skipping discovery" >&2
    exit 0
fi

# --- Publish discovery for this driver's attributes --------------------------
for attribute in $(jq -r 'keys[]' "$DISCOVERY_FILE" 2>/dev/null)
do
    component=$(jq -r ".${attribute}.component // empty" "$DISCOVERY_FILE" 2>/dev/null)
    if [ -z "$component" ]; then
        continue
    fi

    topic="homeassistant/${component}/wmbusmeters/${ID}_${attribute}/config"

    payload=$(jq -c ".${attribute}.discovery_payload" "$DISCOVERY_FILE" 2>/dev/null)
    if [ -z "$payload" ]; then
        continue
    fi

    # substitute placeholders
    payload="${payload//\{name\}/${NAME}}"
    payload="${payload//\{id\}/${ID}}"
    payload="${payload//\{driver\}/${DRIVER}}"
    payload="${payload//\{attribute\}/${attribute}}"

    "$PUB" "$topic" "$payload"
done

exit 0
